apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remote-template-example
  namespace: argocd
spec:
  project: default
  
  source:
    # Repository containing parameter files (template comes from remote URL)
    repoURL: https://github.com/your-org/your-repo
    targetRevision: main
    path: .
    
    plugin:
      name: openshift-template-processor-simple-v1.0
      env:
        - name: TEMPLATE_NAME
          value: https://github.com/redhat-cop/openshift-templates/tree/master/jenkins/jenkins-persistent-template.yml
      parameters:
        - name: APP_NAME
          string: nexus
        - name: APP_NAMESPACE
          string: default
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

